/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "2.2.20"
    id("java")
    id("war")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    flatDir {
        dirs("/User/smcbain/lib")
    }
}
kotlin {
    sourceSets {
        named("main") {
            kotlin.srcDirs("src/main/java","src/main/kotlin")
        }
        named("test") {
            kotlin.srcDirs("src/test/java","src/test/kotlin")
        }
    }
}

sourceSets {
    named("main") {
        java.srcDirs("src/main/java","src/main/kotlin")
    }
    named("test") {
        java.srcDirs("src/test/java","src/test/kotlin")
    }
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation (kotlin("stdlib"))
    implementation ("com.h2database:h2:2.4.240")
    implementation("org.apache.commons:commons-dbcp2:2.13.0")
    compileOnly ("javax.servlet:javax.servlet-api:4.0.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// application {
//    Define the main class for the application.
//    mainClass = "org.example.App"
// }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.war {
        archiveFileName.set("miniglot.war")
}
